### PR TITLE
fix(404): navbar not cover 404 content anymore

### LINKED ISSUE #180: fix nav bar in 404 page
### Describe the bug

Nav bar became too large in 404 page and covered the h1 title.

Screen Shot 2021-10-05 at 10 45 05

### Expected result

NavBar not covered the h1 title.

### Reproduction

https://code-generator.pytorch-ignite.ai/foobar

### Steps to reproduce

View the reproduction link on mobile

### PR DESCRIPTION
**Pull request by rwiteshbera**
A (1)

Now navbar will not cover the h1 tag.

fix #180

### What is the purpose of this pull request?

- [x] Bug fix

### CODE REVIEW

File: src/views/PageNotFound.vue [hunk 1]
```diff
@@ -60,4 +61,13 @@ h1 {
   background: var(--c-white);
   color: var(--c-brand-red);
 }
+
+.footer {
+  position: absolute;
+  bottom: 0;
+  left: 50%;
+  transform: translateX(-50%);
```
Comment (ydcjeff) [inline src/views/PageNotFound.vue:69]:
```suggestion
  left: 0;
  right: 0;
```

**Comment by vfdev-5** [comment]
@rwiteshbera thanks for the PR and the fix ! LGTM, I let @trsvchn or @ydcjeff merge it

**Review by trsvchn — APPROVED** [review]
Thanks @rwiteshbera ! LGTM!
